-- MySQL Script generated by MySQL Workbench
-- Tue May 17 16:33:26 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_camagru
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `db_camagru` ;

-- -----------------------------------------------------
-- Schema db_camagru
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_camagru` DEFAULT CHARACTER SET utf8 ;
USE `db_camagru` ;

-- -----------------------------------------------------
-- Table `db_camagru`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`t_user` (
  `idt_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idt_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_camagru`.`t_img`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`t_img` (
  `idt_img` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `t_imgcol` LONGBLOB NOT NULL,
  `idt_user` INT NOT NULL,
  PRIMARY KEY (`idt_img`),
  INDEX `fk_t_img_t_user_idx` (`idt_user` ASC),
  CONSTRAINT `fk_t_img_t_user`
    FOREIGN KEY (`idt_user`)
    REFERENCES `db_camagru`.`t_user` (`idt_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_camagru`.`t_coment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`t_coment` (
  `idt_coment` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL,
  `idt_img` INT NOT NULL,
  `idt_user` INT NULL,
  PRIMARY KEY (`idt_coment`),
  INDEX `fk_t_coment_t_img1_idx` (`idt_img` ASC),
  INDEX `fk_t_coment_t_user1_idx` (`idt_user` ASC),
  CONSTRAINT `fk_t_coment_t_img1`
    FOREIGN KEY (`idt_img`)
    REFERENCES `db_camagru`.`t_img` (`idt_img`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_coment_t_user1`
    FOREIGN KEY (`idt_user`)
    REFERENCES `db_camagru`.`t_user` (`idt_user`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_camagru`.`t_like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_camagru`.`t_like` (
  `idt_like` INT NOT NULL AUTO_INCREMENT,
  `t_user_idt_user` INT NOT NULL,
  `t_img_idt_img` INT NOT NULL,
  PRIMARY KEY (`idt_like`),
  INDEX `fk_t_like_t_user1_idx` (`t_user_idt_user` ASC),
  INDEX `fk_t_like_t_img1_idx` (`t_img_idt_img` ASC),
  CONSTRAINT `fk_t_like_t_user1`
    FOREIGN KEY (`t_user_idt_user`)
    REFERENCES `db_camagru`.`t_user` (`idt_user`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_like_t_img1`
    FOREIGN KEY (`t_img_idt_img`)
    REFERENCES `db_camagru`.`t_img` (`idt_img`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
